"""empty message

Revision ID: d33676f5b77d
Revises: 2bfbfb220064
Create Date: 2025-03-13 17:16:23.469807

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd33676f5b77d'
down_revision = '2bfbfb220064'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('properties',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('type_client', sa.String(length=50), nullable=False),
    sa.Column('adresse', sa.String(length=200), nullable=False),
    sa.Column('property_type', sa.String(length=50), nullable=False),
    sa.Column('property_name', sa.String(length=100), nullable=False),
    sa.Column('creation_date', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('properties')
    # ### end Alembic commands ###
